In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("IASSIST_LGBTIQ_Data.txt", delimiter="\t", encoding="utf8", dtype={"PubDate":"Int64", "CollectDateStart":"Int64","CollectDateEnd":"Int64"})
dfold = pd.read_csv("IASSIST_LGBTIQ_Data_v1.txt", delimiter="\t", encoding="utf8")
data_dicty = pd.read_csv("data_dictionary.csv", delimiter=";", encoding="utf8")

In [5]:
df

,Title,URL,ResourceType,Citation,PubDate,CollectDateStart,CollectDateEnd,Producer,Distributor,Description,...,Country,GeographicRegion,AdminLevel,UnitAnalysis,Language,Themes,Subjects,Restrictions,Notes,AddedUpdated
0,2013-lgb-living-conditions-persondata. Part of...,https://doi.org/10.18712/NSD-NSD2610-V3,Dataset,NaN,2022,2012,2013,Norman Anderssen,Sikt– Norwegian Agency for Shared Services in ...,2013 lgb-living-conditions-persondata was coll...,...,Norway,Northern Europe,Nation,Individual,Norwegian,"Opinions and Social Attitudes, Sexuality and G...","health, living open and daily life, sexual beh...",No,"On the website, the collection is named ""Sexua...",2025-05-23
1,2015 U.S. Transgender Survey (USTS),https://doi.org/10.3886/ICPSR37229,Dataset,"Sandy E. James, National Center for Transgende...",2019,2015,2015,NaN,Inter university Consortium for Political and ...,The 2015 U.S. Transgender Survey (USTS) was co...,...,United States of America,Northern America,State,Individual,English,"Sexuality and Gender Identity, Discrimination,...","family life and marriage, sexual and gender mi...",Yes,NaN,2025-05-08
2,2020 Census: LGBTQ+,https://www.census.gov/newsroom/press-kits/202...,Website,NaN,2020,2019,<NA>,U.S. Census Bureau,U.S. Census Bureau,The U.S. Census Bureau's Current Population Su...,...,United States of America,Northern America,Nation,Individual,English,Demographic and Vital Statistics,marital status,No,NaN,NaN
3,2024 LGBTI Inclusion Index: Report on the Pilo...,https://www.undp.org/publications/2024-lgbti-i...,Report,NaN,2024,<NA>,<NA>,United Nations Development Programme (UNDP),NaN,The LGBTI Inclusion Index serves as a global b...,...,"Dominican Republic, Georgia, Guyana, New Zeala...",All Regions,Nation,Political or Administrative Area,English,"Opinions and Social Attitudes, Sexuality and G...","employment, health, lgbt or lgbti, transsexual...",No,NaN,2025-02-05
4,2024 U.S. National Survey on the Mental Health...,https://www.thetrevorproject.org/survey-2024/,Report,Trevor Project (2024). 2024 National Survey on...,2024,2023,2023,Trevor Project,Trevor Project,The Trevor Project's 2024 U.S. National Survey...,...,United States of America,Northern America,Nation,Individual,English,"Youth, Health",mental health,No,NaN,2025-04-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,Informe Especial sobre la situación de los der...,https://www.cndh.org.mx/documento/informe-espe...,Report,Comisión Nacional de los Derechos Humanos (201...,2019,<NA>,<NA>,NaN,NaN,National human rights report on LGBTI persons ...,...,Mexico,Latin America and the Caribbean,Nation,Text Unit,Spanish; Castilian,Law and Policy,"human rights, discrimination, policy, legal fr...",No,Spanish-language national human rights report.,2026-03-02
211,Sexual Orientation and Gender Identity (SOGI) ...,https://ihrp.law.utoronto.ca/page/working-grou...,Report,"International Human Rights Program, University...",<NA>,<NA>,<NA>,University of Toronto,University of Toronto,Collection of country-specific memos on legal ...,...,Global,All Regions,Nation,Text Unit,English,Law and Policy,"country conditions, persecution, UN mechanisms...",No,Includes Mexico entries (2010; 2020 updates).,2026-03-02
212,Ipsos LGBT+ Pride Report 2025,https://www.ipsos.com/sites/default/files/ct/n...,Report,Ipsos (2025). LGBT+ Pride Report 2025.,2025,2025,2025,Ipsos,Ipsos,26-country survey tracking attitudes on LGBT+ ...,...,Global,All Regions,Nation,Individual,English,Opinions and Social Attitudes,"marriage, adoption, anti-discrimination, workp...",No,PDF; includes country-level breakouts and gene...,2026-03-02
213,The Experiences of LGBTQ Americans Today,https://www.pewresearch.org/social-trends/2025...,Report,Pew Research Center. (2025). The Experiences o...,2025,2025,2025,Pew Research Center,Pew Research Center,This study seeks to understand the experiences...,...,United States of America,Northern America,Nation,Individual,English,Opinions and Social Attitudes,"same‑sex marriage, adoption, gender recognitio...",No,NaN,NaN
214,U.S. Transgender Survey (USTS),https://ustranssurvey.org/,Report,NaN,2022,2022,2022,U.S. Trans Survey,U.S. Trans Survey,The survey questions covered a wide range of e...,...,United States of America,Northern America,Nation,Individual,English,Opinions and Social Attitudes,"transgender people, gender identity, healthcare",No,NaN,NaN

In [17]:
data_dicty

,Field Names,Description,Link to CV
0,Title,Title of the resource,NaN
1,URL,"URL, DOI or permanent link (if available) for ...",NaN
2,ProDisURL,"Additional URL, DOI or permanent link for the ...",NaN
3,ResourceType,"Type of the data or resource, such as a datase...",#gid=2086916291
4,Citation,Citation for publication or report (any style ...,NaN
5,PubDate,Publication or distribution date in year (YYYY),NaN
6,CollectDateStart,Start date of data collection period in year (...,NaN
7,CollectDateEnd,End date of data collection period in year (YY...,NaN
8,Producer,"Person or organization that authored, collecte...",#gid=1673942145
9,Distributor,"Person or organization that is hosting, publis...",#gid=1673942145
10,Description,Description of the the resource,NaN
11,TimeSpan,Time span that is covered or the date coverage.,NaN
12,Longitudinal,Data that is collected over time (longitudinal...,NaN
13,DataMethodType,The data type or method of data collection is ...,NaN
14,Country,"Country, area (native terrorities), or group o...",gid=1131021598#gid=1131021598
15,GeographicRegion,Name of the geographic region that is covered ...,gid=990806825#gid=990806825
16,AdminLevel,"Administrative or governance level or unit, su...",gid=424615768#gid=424615768
17,UnitAnalysis,The unit for which the data or its variables c...,gid=63348179#gid=63348179
18,Language,"The language of the data, documentation or res...",gid=1322680844#gid=1322680844
19,Themes,One or several themes are assigned to a resour...,gid=1843744120#gid=1843744120
20,Subjects,Subjects are terms assigned by IASSIST members...,gid=549587373#gid=549587373
21,Restrictions,Some data may be restricted in use. This could...,NaN
22,Notes,"Open field for any useful links, notes or comm...",NaN
23,AddedUpdated,Date when entry was added or last updated. For...,NaN

In [10]:
df.columns

Index(['Title', 'URL', 'ResourceType', 'Citation', 'PubDate',
       'CollectDateStart', 'CollectDateEnd', 'Producer', 'Distributor',
       'Description', 'DataMethodType', 'Longitudinal', 'TimeSpan', 'Country',
       'GeographicRegion', 'AdminLevel', 'UnitAnalysis', 'Language', 'Themes',
       'Subjects', 'Restrictions', 'Notes', 'AddedUpdated'],
      dtype='object')

In [11]:
values = {"Title": "<NA>", "URL": "<NA>", "ResourceType": "<NA>", "Citation": "<NA>", "Producer": "<NA>", "Distributor": "<NA>", "Description": "<NA>", "DataMethodType": "<NA>", "Longitudinal": "<NA>", "TimeSpan": "<NA>", "Country": "<NA>", "GeographicRegion": "<NA>", "AdminLevel": "<NA>", "UnitAnalysis": "<NA>", "Language": "<NA>", "Themes": "<NA>", "Subjects": "<NA>", "Restrictions": "<NA>", "Notes": "<NA>", "AddedUpdated":"<NA>"}

df.fillna(value=values)

,Title,URL,ResourceType,Citation,PubDate,CollectDateStart,CollectDateEnd,Producer,Distributor,Description,...,Country,GeographicRegion,AdminLevel,UnitAnalysis,Language,Themes,Subjects,Restrictions,Notes,AddedUpdated
0,2013-lgb-living-conditions-persondata. Part of...,https://doi.org/10.18712/NSD-NSD2610-V3,Dataset,<NA>,2022,2012,2013,Norman Anderssen,Sikt– Norwegian Agency for Shared Services in ...,2013 lgb-living-conditions-persondata was coll...,...,Norway,Northern Europe,Nation,Individual,Norwegian,"Opinions and Social Attitudes, Sexuality and G...","health, living open and daily life, sexual beh...",No,"On the website, the collection is named ""Sexua...",2025-05-23
1,2015 U.S. Transgender Survey (USTS),https://doi.org/10.3886/ICPSR37229,Dataset,"Sandy E. James, National Center for Transgende...",2019,2015,2015,<NA>,Inter university Consortium for Political and ...,The 2015 U.S. Transgender Survey (USTS) was co...,...,United States of America,Northern America,State,Individual,English,"Sexuality and Gender Identity, Discrimination,...","family life and marriage, sexual and gender mi...",Yes,<NA>,2025-05-08
2,2020 Census: LGBTQ+,https://www.census.gov/newsroom/press-kits/202...,Website,<NA>,2020,2019,<NA>,U.S. Census Bureau,U.S. Census Bureau,The U.S. Census Bureau's Current Population Su...,...,United States of America,Northern America,Nation,Individual,English,Demographic and Vital Statistics,marital status,No,<NA>,<NA>
3,2024 LGBTI Inclusion Index: Report on the Pilo...,https://www.undp.org/publications/2024-lgbti-i...,Report,<NA>,2024,<NA>,<NA>,United Nations Development Programme (UNDP),<NA>,The LGBTI Inclusion Index serves as a global b...,...,"Dominican Republic, Georgia, Guyana, New Zeala...",All Regions,Nation,Political or Administrative Area,English,"Opinions and Social Attitudes, Sexuality and G...","employment, health, lgbt or lgbti, transsexual...",No,<NA>,2025-02-05
4,2024 U.S. National Survey on the Mental Health...,https://www.thetrevorproject.org/survey-2024/,Report,Trevor Project (2024). 2024 National Survey on...,2024,2023,2023,Trevor Project,Trevor Project,The Trevor Project's 2024 U.S. National Survey...,...,United States of America,Northern America,Nation,Individual,English,"Youth, Health",mental health,No,<NA>,2025-04-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,Informe Especial sobre la situación de los der...,https://www.cndh.org.mx/documento/informe-espe...,Report,Comisión Nacional de los Derechos Humanos (201...,2019,<NA>,<NA>,<NA>,<NA>,National human rights report on LGBTI persons ...,...,Mexico,Latin America and the Caribbean,Nation,Text Unit,Spanish; Castilian,Law and Policy,"human rights, discrimination, policy, legal fr...",No,Spanish-language national human rights report.,2026-03-02
211,Sexual Orientation and Gender Identity (SOGI) ...,https://ihrp.law.utoronto.ca/page/working-grou...,Report,"International Human Rights Program, University...",<NA>,<NA>,<NA>,University of Toronto,University of Toronto,Collection of country-specific memos on legal ...,...,Global,All Regions,Nation,Text Unit,English,Law and Policy,"country conditions, persecution, UN mechanisms...",No,Includes Mexico entries (2010; 2020 updates).,2026-03-02
212,Ipsos LGBT+ Pride Report 2025,https://www.ipsos.com/sites/default/files/ct/n...,Report,Ipsos (2025). LGBT+ Pride Report 2025.,2025,2025,2025,Ipsos,Ipsos,26-country survey tracking attitudes on LGBT+ ...,...,Global,All Regions,Nation,Individual,English,Opinions and Social Attitudes,"marriage, adoption, anti-discrimination, workp...",No,PDF; includes country-level breakouts and gene...,2026-03-02
213,The Experiences of LGBTQ Americans Today,https://www.pewresearch.org/social-trends/2025...,Report,Pew Research Center. (2025). The Experiences o...,2025,2025,2025,Pew Research Center,Pew Research Center,This study seeks to understand the experiences...,...,United States of America,Northern America,Nation,Individual,English,Opinions and Social Attitudes,"same‑sex marriage, adoption, gender recognitio...",No,<NA>,<NA>
214,U.S. Transgender Survey (USTS),https://ustranssurvey.org/,Report,<NA>,2022,2022,2022,U.S. Trans Survey,U.S. Trans Survey,The survey questions covered a wide range of e...,...,United States of America,Northern America,Nation,Individual,English,Opinions and Social Attitudes,"transgender people, gender identity, healthcare",No,<NA>,<NA>

In [3]:
df["PubDate"]

0      2022
1      2019
2      2020
3      2024
4      2024
       ...
210    2019
211    <NA>
212    2025
213    2025
214    2022
Name: PubDate, Length: 215, dtype: Int64

In [27]:
df.dtypes

Title               object
URL                 object
ResourceType        object
Citation            object
PubDate              Int64
CollectDateStart    object
CollectDateEnd      object
Producer            object
Distributor         object
Description         object
DataMethodType      object
Longitudinal        object
TimeSpan            object
Country             object
GeographicRegion    object
AdminLevel          object
UnitAnalysis        object
Language            object
Themes              object
Subjects            object
Restrictions        object
Notes               object
AddedUpdated        object
dtype: object

In [8]:
dfold.dtypes

Title                object
URL                  object
ResourceType         object
Citation             object
PubDate             float64
CollectDateStart    float64
CollectDateEnd      float64
Producer             object
Distributor          object
Description          object
DataMethodType       object
Longitudinal         object
TimeSpan             object
Country              object
GeographicRegion     object
AdminLevel           object
UnitAnalysis         object
Language             object
Themes               object
Subjects             object
Restrictions         object
Notes                object
AddedUpdated         object
Unnamed: 23         float64
Unnamed: 24         float64
Unnamed: 25         float64
Unnamed: 26         float64
Unnamed: 27         float64
Unnamed: 28         float64
Unnamed: 29         float64
dtype: object

In [6]:
#controlled vocabularies (2025-06-11)
cv_resourceType = ["All","Artwork","Audiovisual","Bibliography","Blog","Book","Book Chapter","Collection","Computational Notebook","Conference Paper","Conference Proceeding","Controlled Vocabulary","Data Dashboard","Data Database","Data Journalism","Data NGO","Data Paper","Data Repository","Dataset","Directory","Dissertation","Event","Finding Aid","Funding Source","Geospatial","Guide and Handbook","Image","Instrument","Interactive Resource","Journal","Journal Article","LibGuide","Manuscript","Map","Model","Network","Oral History","Other","Output Management Plan","Peer Review","Physical Object","Poster","Preprint","Program","Project or Pilot","Report","Scholar or Expert","Service","Social Media","Software","Sound","Standard","Statistics","Study Registration","Text","Website","Workflow"]
cv_producer = ["All","1000 Genomes – A Deep Catalog of Human Genetic Variation","45 and Up Study","4TU.Centre for Research Data","ABACUS Dataverse Network","Aberdeen Children of the 1950s Study","ACEpepDB Peptide Database of Central Food Technological Research Institute","Adaptive Biotechnologies","Advanced Cooperative Arctic Data and Information Service","AEKOS Data Portal","Afrobarometer","Ag Data Commons","Agency for Healthcare Research and Quality","Agricultural and Environmental Data Archive","Alaska Ocean Observing System","Alexandria Archive Institute","Alfred Wegener Institute for Polar and Marine Research/Center for Marine Environmental Sciences","American College of Surgeons","American Museum of Natural History","American Society for Cell Biology","AmeriFlux","Amsterdam Cohort Studies on HIV infection and AIDS","Amsterdam Health Service","Analysis of the Interstellar Medium of Isolated Galaxies (AMIGA)","Animal QTL Database","Anja Perry","Archaeology Data Service","Archigos: A Data Base on Leaders 1875 – 2004","Argonne National Laboratory","ArrayExpress Archive","ASCL Advisory Committee","Asia-Pacific Coalition on Male Sexual Health (APCOM)","Asia-Pacific Transgender Network (APTN)","Aspergillus Genome Database","Aston Data Explorer","Aston University","Astrophysical Research Consortium","Astrophysics Source Code Library","Atmosphere to Electrons (A2e) Data Archive and Portal","Atmospheric Radiation Measurement Program","ATNF Pulsar Database","Aukland University of Technology","Australian Antarctic Data Centre","Australian Antarctic Division","Australian Catholic University – Research Bank","Australian Data Archive","Australian Institute of Marine Science","Australian National University","Avon Longitudinal Study of Parents and Children (ALSPAC)","BacDive","Bacterial Carbohydrate Structure DataBase","Barcode of Life Data System","Bavarian Archive for Speech Signals (BAS)","Baylor College of Medicine","BC Data Catalogue","BC Government","Behavioral Risk Factor Surveillance System (BRFSS)","Beijing Genomics Institute","Benchfly","Biocode Commons","Bioconductor","BioCyc Collection of Pathway/Genome Databases","BioDare – Biological Data Repository","Biodiversity Institute of Ontario","Biodiversity Research Center, Academia Sinica","Biological and Chemical Oceanography Data Management Office","Biological Magnetic Resonance Data Bank","Blackfirer Technology Inc.","Bloomsbury Academic","Bolin Centre Database","BonaRes Repository","Borealis","Born in Bradford Cohort Study","Boston University","BrainLife","Breast Cancer Surveillance Consortium","Bruegel","Bristol University","British Oceanographic Data Centre","Broad Institute","Broad Institute Genome Data Analysis Center","Broad Novartis Cancer Cell Line Encyclopedia","BsubCyc: Encyclopedia of B. subtilis Genes and Metabolism","Buckeye Speech Corpus","caArray","California Institute of Technology","CaltechDATA","Cambridge Structural Database","Canadian Association of Research Libraries","Canadian Opinion Research Archive","Cancer GEnome Mine","Cancer Models Database","cancer Nanotechnology Laboratory","Candida Genome Database","CaPSURE","Carbohydrate Structure Database","Carnegie Institution for Science","Carnegie Mellon University","Cell Centered Database","Cellular Phenotype Database","Center for American Progress (CAP)","Center for European Nuclear Research","Center for International Forestry Research","Center for International Forestry Research Dataverse","Center for Open Science","Center for Research Data in Psychology (PsychData)","CentERdata, Tilburg University","Centers for Disease Control and Prevention","Central Food Technological Research Institute","Centre De Donnees Astronomiques De Strasbourg","Centre for Environmental Data Analysis","Centre national de la recherche scientifique (CNRS)","CERN Open Data Portal","Chapman University Digital Commons","Charles University in Prague, UFAL","Chemical Effects in Biological Systems","chemotion","Chickpea Transcriptome Database","Child Language Data Exchange System (CHILDES)","Chinese Academy of Sciences","cIRcle","CISER Data Archive","Climate Hazards Group Data Archive","CMCC","COD Advisory Board","Code Ocean","Code Ocean, Inc.","Codex Sinaiticus","Cognitive Function and Ageing Study","Coherent X ray Imaging Data Bank","Cold and Arid Regions Science Data Center at Lanzhou","Collaborative Research in Computational Neuroscience (CRCNS.org)","Columbia University","Columbia University Academic Commons","ComBase – A combined database and predictor of bacterial responses to food related environments","Commonwealth Scientific and Industrial Research Organization","Comparative Political Data Set","Comparative Welfare Entitlements Dataset 2","Comprehensive R Archive Network","Compton D.R.; Meadow T; and Schilt K","Computational and Information Systems Laboratory Research Data Archive","Computational Geometry Algorithms Library","Concordia University","Consortium of European Social Science Data Archives (CESSDA)","Consortium for Social, Behavioral, Educational and Economic Sciences (KonsortSWD) ","Consortium of Universities for the Advancement of Hydrologic Science Inc. (CUAHSI)","Constituency Level Elections Archive","Cornell University","Correlates of War Project","CORUM The Comprehensive Resource of Mammalian protein complexes","CPLA","Cross National Equivalent File","Crystallography Open Database","CSD Health Research","CSIC UTM Marine Technology Unit","CSIRO Data Access Portal","Curtin University","Curtin University Research Data","Dallas Heart Study","Danish National Archives ","Danish National Birth Cohort","Data Archiving and Networked Services (DANS)","Data Repository for the University of Minnesota","data.bris Research Data Repository","Data.gov","Database of Protein Disorder","Database of Zeolite Structures","Databrary","DataverseNL","DataverseNO","Dataweb","Deakin Research Online","Deakin University","Deep Blue Data","DEG, a database of essential genes","Delft University of Technology/Eindhoven University of Technology/University of Twente","DesignSafeCI","Deutsche Bundesbank","Diabetes Study of Northern California","Digital Repository at the University of Maryland","Digital Science","Digital.CSIC","DOE Geothermal Data Repository","DR NTU (Data)","Drabinski Emily","Drosophila Genetic Reference Panel 2","Drosophila Synthetic Population Resource","DrugBank","Dryad","Duke University","Durham University, CERN","Earthbound Planet Search","EAWAG Biocatalysis/Biodegradation Database","eBird","EcoCyc: Encyclopedia of E. coli Genes and Metabolism","EcoGene","Ecological Society of Japan","eCrystals – Southampton","eData: the STFC Research Data Repository","Edinburgh DataShare","Edinburgh University","Electron Microscopy Data Bank","EMAGE Gene Expression Database","EMBL EBI/Swiss Institute of Bioinformatics/Protein Information Resource","EMBL European Bioinformatics Institute","Energy Data eXchange","English Lexicon Project","Enlighten Research Data","Environmental Data Explorer","Environmental Data Initiative","Environmental Dataset Gateway","Envronmental Protection Agency","Equal Ground Sri Lanka","Equaldex","Ernst Moritz Arntz University","ESS DIVE","ESTerases and alpha/beta Hydrolase Enzymes and Relatives","ETH Data Archive","ETH Zurich Research Collection","ETS Data","EUDAT Collaborative Data Infrastructure","EUROCAT – European Surveillance of Congenital Anomalies","EUROMOD","European Bioinformatics Institute","European Centre for Medium Range Weather Forecasts","European Commission","European Commission Institute for Energy and Transport","Human European Consultancy","European Molecular Biology Laboratory","European Nucleotide Archive","European Organization for Nuclear Research","European Synchrotron Radiation Facility","European Union Agency for Fundamental Rights (FRA)","Eurostat","eyeMoviePedia","eyesMoviePedia gGmbH","Federated Research Data Repository","Figshare","Finnish Social Science Data Archive","FLOSSmole","FlowRepository","Fluxnet","Forest Service Research Data Archive","Forschungsstelle Partner- und Sexualforschung der Gesellschaft für Sexualwissenschaften, Leipzig","Fragile Families and Child Wellbeing Study","Gazel Cohort","Gdansk University of Technology","GenBank","Gene Expression Omnibus","GenomeRNAi","GeoData Institute – University of Southampton","GEOROC","Geoscientific Data and Discovery Publishing System (Geology in China)","German Astronomical Virtual Observatory","German Astrophysical Virtual Observatory Data Center","German Cancer Research Center","German Centre for Gerontology","German Centre for Gerontology (Deutsches Zentrum fuer Altersfragen)","German Climate Computing Centre","German Health Interview and Examination Survey for Children and Adolescents (KiGGS)","German Institute for Economic Research","GESIS - Leibniz Institute for the Social Sciences","GFZ German Research Centre for Geosciences","GigaDB","Global Biodiversity Information Facility","Global Catalogue of Microorganisms","Global Change Research Data Publishing and Repository","Global Fund to Fight AIDS, Tuberculosis and Malaria (‘The Global Fund’)","Global Hydrology Resource Center, NASA Distributed Active Archive Center","Global Network of Isotopes in Precipitation","Global Terrorism Database","Global Trade, Assistance, and Production: The GTAP Data Base","Golm Metabolome Database","Gordon Conwell Theological Seminary","Great East Japan Earthquake Special Survey (GEES)","Greater London Authority","greengenes","GroupLens Datasets","Growing Up Today Study","Gulf of Alaska Data Portal","Gulf of Mexico Research Initiative Information and Data Cooperative Management System","Guyan K","GWAS Central","Hakai","Hakai Institute","Harvard College","Harvard Dataverse","Harvard Medical School","Harvard Medical School – Library of Integrated Network Based Cellular Signatures","Harvard Smithsonian Center for Astrophysics","Harvard University","Health Improvement Network","Healthcare Cost and Utilization Project (HCUP)","heiDATA Dataverse Network","Heidelberg University","Helmholtz Centre","HEPData","HepSim","High Resolution Transmission Molecular Absorption Database","History of Marine Animal Populations","Homosaurus.org","Household, Income and Labour Dynamics in Australia (HILDA) Survey","HSRC Research Data Centre","Human Genome Variation Society","Human Metabolome Database","HumanCyc: Human Metabolic Database","Humboldt Universität zu Berlin","HydroShare","ICRISAT Dataverse","ICTWSS: Database on Institutional Characteristics of Trade Unions, Wage Setting, State Intervention and Social Pacts in 34 countries between 1960 and 2014","IEDA: Marine Geoscience Data System","IEEE","IEEE DataPort","ifo Institute","Ifremer","ILGA Europe","immuneACCESS","Imperial College High Performance Computing Service Data Repository","Imperial College London","Imperial College London/DSpace","InCHIANTI Group","InCHIANTI Study","Incorporated Research Insitutions for Seismology","Incorporated Research Institutions for Seismology Data Management Center","INDEPTH Data Repository","INDEPTH Network","Indiana University School of Medicine","Infevers","Information Marketplace for Policy and Analysis of Cyber Risk and Trust","INRA Centre de Montpellier","Inserm","Institut Laue Langevin","Institute for Infocomm Research","Institute for Diversity and Anti-Discrimination Research IDA","Institute for Quantitative Social Science","Institute of Astrophysics of Andalucia","Institute of Food Research","Institute of Geographical Sciences and Natural Resources Research, Chinese Academy of Sciences","Institute of Systems Biology","Instituto de Engenharia de Sistemas e Computadores, Investigacao e Desenvolvimento","INTEGRALL: The Integron Database","Integrated Carbon Observation System","Inter university Consortium for Political and Social Research ICPSR","International Atomic Energy Agency","International Council for the Exploration of the Sea","International Council for the Exploration of the Sea (ICES) datasets","International Geoid Service","International HapMap Project","International Service for the Geoid","International Society for Advancement of Cytometry (ISAC)","International Soil Carbon Network","Iowa Research Online","IPUMS","ISRIC  World Soil Information / World Data Centre for Soils","ISRIC World Soil Information","Jackson Laboratory","Jan Carel Warffemius","Japan Agency for Marine Earth Science and Technology","Japan Chemical Substance Dictionary (Nikkaji)","Japan Child Panel Survey (JCPS)","Japan Household Panel Survey (JHPS/KHPS)","Japan Long Term Ecological Research Network Database","Japan Science and Technology Agency (JST)","Japanese Panel Survey of Consumers (JPSC)","JGI Genome Portal","Johns Hopkins University","Johns Hopkins University Data Archive","Joint United Nations Programme on HIV/AIDS","Jonas Recker","JRC Data Catalogue","Kaiser Permanente","Karlsruher Institut für Technologie – Institut für Organische Chemie","Kent Ridge Bio medical Dataset Repository","KiMoSys: an experimental data repository for KInetic MOdels of biological SYStems","Kinder Institute Urban Data Platform","King’s College","KNB Data Repository","KNMI Data Platform","Knowledgebase of Interatomic Models","Knowledgebase of Interatomic Models (KIM) project","Korea Labor Institute","Korea Polar Data Center","Korean Labor and Income Panel Study","Land Information New Zealand Data Service","Lawrence Berkeley National Laboratory","Lawrence Berkeley National Laboratory.","LearnLab DataShop","Legacy Archive for Microwave Background Data Analysis (LAMBDA)","Leibniz Centre for Agricultural Landscape Research (ZALF)","Leibniz Institute","Leibniz Institute for Educational Trajectories","Leibniz Institute for Psychology Information","Leibniz Institute for Social Sciences","Leland Stanford Junior University","Leland Stanford Junior University and Broad Institute","Leuphana University","LGBTQ+ Victory Institute","LibraData – University of Virginia Dataverse","LINDAT/CLARIN Centre for Language Research Infrastructure Digital Repository","LISS panel data","LMU ifo Economics and Business Data Center","London Datastore","Longitudinal Aging Study Amsterdam","Maddison Project","Malaria Atlas Project","Manchester University","Manitoba Centre for Health Policy Population Health Research Data Repository","Mantid Project","Marie Stopes International","Marie-Ang Schiltz","Marine and Hydrokinetic Data Repository","Mass Spectrometry Interactive Virtual Environment","Massachusetts College of Pharmacy","Massachussetts Institute of Technology","MassBank","MATDAT Materials Properties Database","MatDB","Materials Data Repository","Max Planck Institute for Chemistry","Max Planck Institute for Ornithology","Max Planck Institute for Social Law and Social Policy","Max Planck Institute of Molecular Plant Physiology","Medical Expenditure Panel Survey","Medical Research Council","Mendeley","Mendeley Data","MetaboLights","MetaCyc: Metabolic Pathway and Enzyme Database","Mexican Health and Aging Study","Michael Pollak","Michgan State College of Law","Michigan Corpus of Academic Spoken English","MiCroKit","Mikulski Archive for Space Telescopes","Million Song Dataset","miRBase","Mirovni inštitut - The Peace Institute ","Model Organism ENCyclopedia of DNA Elements","ModelDB","modENCODE Consortium","Monash University","MorphoBank","MorphoSource","Most Wiedzy Open Research Data Catalog","Mouse Phenome Database","Movebank Data Repository","MRC Human Genetics","MRC National Survey of Health and Development","MRC Social and Public Health Sciences Unit","Multi Regional Clinical Trials Center of Brigham and Women’s Hospital and Harvard","nanoHUB","Nanyang Technological University","Nara Institute of Science and Technology","NASA Socioeconomic Data and Applications Center","NASA/IPAC Infrared Science Archive","National Aeronautics and Space Administration","National Cancer Data Base","National Cancer Institute","National Center for Atmospheric Research","National Center for Biotechnology Information (NCBI)","National Center for Earth Surface Dynamics Data Repository","National Data Archive on Child Abuse and Neglect","National Energy Technology Laboratory","National Evolutionary Synthesis Center","National Gay & Lesbian Chamber of Commerce (NGLCC)","National Geological Archives of China","National Institute for Basic Biology","National Institute for Materials Science","National Institute of Advanced Industrial Science and Technology","National Institute of Environmental Health Sciences","National Institute of Plant Genome Research, Aruna Asaf Ali Marg","National Institute of Standards and Technology","National Institutes of Health","National Library of Medicine","National Oceanic and Atmospheric Administration","National Renewable Energy Laboratory","National Research Foundation","National Science Foundation/National Institutes of Health","National Sleep Research Resource","National Snow and Ice Data Center","Natural Environmental Research Council","NCAR Atmospheric Chemistry Observations and Modeling","NCAR Climate and Global Dynamics","NCAR Earth Observing Laboratory","NCAR Geoscience Data Exchange (GDEX)","NCAR Mesoscale and Microscale Meteorological Laboratory","NCAR Research Applications Laboratory","NCBI","NDEx – The Network Data Exchange","Neotoma Paleoecology Database","NERC – British Antarctic Survey","NERC – British Geological Survey","NERC – Centre for Ecology and Hydrology","NERC Environmental Information Data Centre","NERC National Geoscience Data Centre","New York University","New Zealand Government","NGEE – Tropics","NGEE Arctic Data Catalog","NIRD Research Data Archive","NIST Atomic Spectra Database","nmrshiftdb2","NOAA","NOAA National Centers for Environmental Information","NOAA Paleoclimatology","Nord Trondelag Health Study","Norman Anderssen","North Carolina State University","Norwegian Polar Data Centre","Norwegian Polar Institute","Norwegian University of Science and Technology","Norwegian Women and Cancer Study","NREL Data Catalog","NSF Arctic Data Center","Nucleic Acid Database","Oak Ridge Leadership Computing Facility","Oak Ridge Leadership Computing Facility (OLCF) Constellation Portal","Oak Ridge National Laboratory","Oak Ridge National Laboratory Distributed Active Archive Center for Biogeochemical Dynamics","OECD iLibrary","Office for National Statistics","Ohio State University","OHSU Digital Commons","Old Bailey Proceedings Online","Ontario Council of University Libraries","OPA – Ocean Predictions and Applications","Open Access Series of Imaging Studies (OASIS)","Open Context","Open Science Framework","OpenNeuro","OpenTopography Facility","ORA – Oxford University Research Archive","Oregon Health and Science University","Oregon State University","Organisation for Economic Co operation and Development","OsloMet","OsteoArthritis Initiative","Outright International","Oxford University Press","Pacific Islands Families Study","Pacific Northwest National Laboratory","Panel On Household Finances","PANGAEA","Partnership for Interdisciplinary Studies of Coastal Oceans (PISCO)","Pathogen Host Interactions database","Peking University","Peking University Open Research Data Platform","Penn State University","Penn World Table","Pennsylvania State University","PeptideAtlas","Pew Research Center","PhysioNet","Pitt Quantum Repository","Pittsburgh Science of Learning Center","Planetary Data System","Plant and Fungal Carbohydrate Structure Database","Plant Organelles Database 3","Plant Transcription Factor Database","Polar Data Catalogue","PRIDE","Princeton University","PRISM Climate Data","Prognostics Center of Excellence Data Repository","Project Achilles","PseudoBase","PsychArchives","PUB – Publications at Bielefeld University","Purdue University","Purdue University Research Repository","QTL Archive","Quality of Government Institute Data","Queen’s University Belfast","Queens Research Portal","Queens University","Queensland University of Technology","Queer Metadata Collective","QUT Research Data Finder","Reality Commons","REasons for Geographic and Racial Differences in Stroke Study","Recode","REFOLD","RefSeq","Repository and Open Science Access Portal","Research Centre for Environment and Health","Research Data Center at LIfBi","Research Data Center Socio Economic Panel","Research Data Centre at IQB","ResearchCompendia.org","RESID Database of Protein Modifications","Rice University","Richard Köhler","Ridwan Islam Sifat","RiuNet","Robert Koch Institute","Rolling Deck to Repository (R2R) Program","Romani Morpho Syntax Database","Roper Center for Public Opinion Research","Roswell Park Cancer Institute","Rothamsted Research","Royal Netherlands Academy of Arts and Sciences/Netherlands Organisation for Scientific Research","Royal Netherlands Meteorological Institute","Russian Academy of Sciences","Rutgers University","Rutgers University Community Repository","Sax Institute","SBGrid Data Bank","Sceince and Technology Facilities Council","Scholar@UC","ScholarlyCommons","Scholars Bank","ScholarsArchive@OSU","Science and Technology Facilities Council","Science Data Bank","Sciences Po (Centre de données socio-politiques CDSP)","SciLifeLab","SciLifeLab Data Repository","SEANOE","SFU Research Data Repository","SHARE – Survey of Health, Ageing and Retirement in Europe","Signaling Pathways Project","Sikt– Norwegian Agency for Shared Services in Education and Research","Simon Fraser University","SIOExplorer","Sloan Digital Sky Survey","Slovenian Social Science Data Archives (ADP) ","Small Angle Scattering Biological Data Bank","Smithsonian Institution","Smithsonian Research Online","Sociaal en Cultureel Planbureau (SCP) (Netherlands Institute for Social Research)","Social Science Japan Data Archive","SOCIB","South African Data Archive","Space Telescope Science Institute","Spectral Database for Organic Compounds (SDBS)","Spectrum Research Repository","SRI International","Stanford Center for Reproducible Neuroscience","Stanford Microarray Database","Stanford University","Statens Serum Institut","Statista","Statistics Canada","Stemformatics","STFC ISIS Neutron and Muon Source","Stockholm University","Stonewall","Strasbourg Observatory","Study of Health in Pomerania","SuiteSparse Matrix Collection","Supreme Court Database","Surrey Research Insight","Survey Research Data Archive Taiwan","SWATHAtlas","Swedish National Data Service, SND","Swiss HIV Cohort Study","SWISSbase - Swiss Centre of Expertise in the Social Sciences FORS ","Syracuse University","Taiwan Biodiversity Information Facility","Taiwan Forestry Research Institute","Taiwan Forestry Research Institute Data Catalog","TalkBank","TARDIS","Temple University","Texas AandM University","Texas AandM University  Corpus Christi","Texas Data Repository Dataverse","TGEU Trans Europe and Central Asia","The Association of Religion Data Archives","The Cancer Imaging Archive","The Cell: An Image Library","The Library Quarterly, The University of Chicago Press","The Materials Project","The Open University","The University of York","Tianjin University","Trans Metadata Collective","TreeBASE","Trevor Project","TwinsUK","U. S. Bureau of Justice","U.S. Census Bureau","U.S. Census Bureau TIGER/Line Shapefiles","U.S. County Level Social Capital Data","U.S. Department of Agriculture","U.S. Department of Energy","U.S. Government","U.S. National Archives and Records Administration","U.S. National Institutes of Health (NIH)","U.S.. National Archives and Records Administration Dataverse","UAL Dataverse","UC San Diego","UC San Diego Library Digital Collections","UC San Francisco","UCD Digital Library","UCI Machine Learning Repository","UCLA Phonetics Lab Archive","UK Data Archive","UK National Health Service","UK National Statistics","UK Polar Data Centre","UK Reading Experience Database","UNAVCO Geodesy Data Archive","UNC Dataverse","UNINETT","UniPROBE (Universal PBM Resource for Oligonucleotide Binding Evaluation) Database","UniProt Knowledgebase","UNITE","United Nations (UN)","United Nations Development Programme (UNDP)","United Nations Educational, Scientific and Cultural Organization (UNESCO)","United Nations Environment Programme (UNEP)","United Nations International Children’s Fund (UNICEF)","United Nations Population Fund (UNICEF)","United States Agency for International Development (USAID)","United States Department of Agriculture","United States Department of Energy","United States Department of Housing and Urban Development","United States Department of the Interior","United States Department of Transportation","United States Geological Survey","Universidade de Aveiro and Sindesi, Lda.","Università degli Studi di Torino","Universitat Bielefeld","Universitat Politecnica de Valencia","University College Cork","University College Dublin","University College London","University Corporation for Atmospheric Research","University Navstar Consortium","University of Aberdeen","University of Adelaide","University of Alabama","University of Alberta","University of Amsterdam","University of Bath","University of Bath Research Data Archive","University of Berne","University of Birmingham","University of Bristol","University of British Columbia","University of Califormia, Santa Barbara","University of California","University of California at Berkeley","University of California Press","University of California, Davis","University of California, Los Angeles","University of California, San Diego","University of California, Santa Barbara","University of Cambridge","University of Cincinatti","University of Colorado","University of Connecticut","University of Edinburgh","University of Edmonton","University of Essex","University of Glasgow","University of Gothenberg","University of Gothenburg","University of Groningen","University of Helsinki","University of Iowa","University of Kansas","University of Köln","University of Leicester","University of Leiden","University of Manchester","University of Manitoba","University of Maryland","University of Melbourne","University of Miami","University of Michigan","University of Minnesota","University of Munich","University of North Carolina","University of Oregon","University of Oxford","University of Pittsburgh","University of Prince Edward Island","University of Queensland","University of Reading","University of Reading Research Data Archive","University of Rijeka","University of San Diego","University of Science and Technology of China","University of Sheffield","University of Southampton","University of Southampton Institutional Repository","University of Surrey","University of Tampere","University of Tartu","University of Texas Medical Branch","University of Texas Southwestern Medical Center","University of Tokyo","University of Tromso","University of Ulster","University of Waterloo","University of Wisconsin","University of York","University of Zurich","Univiersity of Tromso","UPEI Data Repository","UQ eSpace","Utrecht University","Varieties of Democracy","Vienna University of Economics and Business","Vietnam Studies Group","Vivli","VLIZ – Flanders Marine Institute","VU University Amsterdam","Washington University in St. Louis","West of Scotland Twenty 07 Study","Whitehall II Study","Williams Institute","Woods Hole Oceanographic Institution","Woods Hole Open Access Server","Work Histories Italian Panel","World Bank","World Christian Database","World Contraceptive Use 2014","World Data Centre for Climate","World Glacier Monitoring Service (WGMS)","World Health Organization (WHO)","World Religion Database","World terms Survey","World Values Survey Association","WorldPop","Worldwide Governance Indicators Project","Worldwide Protein Data Bank","Worldwide Protein Data Bank (Consortium)","Wormbase","Yale Open Data Access (YODA) Project","Yale University","Yeast Resource Center Public Image Repository","YODA","York Research Database","York University","York University Digital Library","Zenodo","Zentralinstitut für Jugendforschung","History Commons (formerly Accessible Archives)","Coherent Digital"]
cv_themes = ["All","Civil and Political Rights","Contributions","Criminal Justice","Demographic and Vital Statistics","Discrimination","Family and Marriage","Health","Indigeneous People","Law and Policy","Migration and Immigration","Movements","Opinions and Social Attitudes","Sexuality and Gender Identity","Social Justice and Equality","Socio-economic-cultural","Youth"]
cv_subject = ["All","abortion","activisim","adoption","advertising","affirmative action","african americans","aging","hiv/aids","anti-semitism","anxiety","arraignment","arrest","art","asian americans","asexual","asexual people","assault weapons","asylum ","attitudes","bibliography","bisexuals","black lives matter","black white relations","blood donation","bullying","business ","cancer","cardiovascular disease","child abuse","child development","child welfare","children","cisgender","citizen crime reporting","citizen grievances","citizenship","civil rights","climate and environmental justice","climate change","colonialism","communities","commuting","companies","concentration camp","conversion therapy","corporal punishment","correctional facilities","covid-19","crime","crime and public safety","crime rates","criminal justice","criminal justice system","criminal law","cross-national","culture","daily life","death","demonstrations","detention","diabetes","disabilities","discrimination","disorders and medical conditions","disposition (legal)","domestic violence","drug overdose","early life conditions","economic change","economic development","economics","education","election law","elections","employment","end of KZ-detention; manner of end","environment","environmentalism","equality and inequality ","ethnic discrimination","ethnic groups","ethnicity","families","family life and marriage","fear of crime","finance and financial institutions","firearms","forced migration","fraud","freedom","gay","gay couples","gender roles","gender expression","gender identity","gender nonconformity","gender stereotypes","gender transition","genetics data","germany","gis data","government","gun control","harassment","hate crimes","health","health promotion","health disparities or health equity","healthcare","heart disease","heterosexual","higher education","hispanic or latino americans","hiv-positive persons","home ownership","homicide","homophobia","homosexual","homosexuality","housing","human rights","human services","identity","illegal immigrants","immigrants","immigration","immigration policy","imprisonment","incarceration","incarceration date","income and wealth","indicators or indexes","indigeneous people","infrastructure (water)","injuries","inmates","intersex people","intersex","intolerance","jail inmates","jewish americans","jewish people","jim crow laws","juvenile inmates","juveniles","labor","labor force or labor supply","labor organizations","labor unions","land dispossession","land ownership","law and legislation","law enforcement","legislation","length of police detention","length of previous convictions","lesbians","lgbt or lgbti","life sentences","living open and daily life","loans and debts","longitudinal data","lynching","marital status","maximum security","media use","medicine","mental health","mental health services","mental illness","migrants","migration","military","minorities","mortgages","movements","music","muslims","native americans","natural disasters","neighborhoods","newspapers","nonbinary","nonviolent crime","north carolina","obesity","occupations","offenses","opinions","pandemic","parents","parole","philanhtropy","place of incarceration","police","police brutality","police citizen interaction","police citizen interactions","police community relations","police equipment","police harrasment","police harrassment","police misconduct","police performance","police response","police safety","police shootings","police training","police use of deadly force","police use of force","police use of force victims rights","police violence","police weapons","policies and procedures","policy","political attitudes","political participation","political protests","politics","population characteristics","population estimates","population migration","populations","poverty","prejudice","prisons","property","protest camps","protest movements","psychiatry","public assistance","public health","public opinion","public relations","public schools","public welfare","race","race and ethnicity","race discrimination","race relations","racial attitudes","racial discrimination","racial equity/inequity","racial segregation","racism","real estate","reason for incarceration","refinancing","refugees","relationship","religion","religious persecution","renal disease","rental housing","reparations","reproductive health","research","respiratory diseases","rights awareness","same-sex marriage","same-sex ","segregation","sentences and sentencing","sexual and gender minorities","sexual behavior","sexual orientation","slaves","social activism","social attitudes and government response","social change","social exclusion","social inclusion","social justice","social mobility","social movements","social networks","social policy","social stratification","special position","specific diseases","sports","stigma","students","substance abuse","suicide","technology","terminology","toleration","tourism","trans-specific questions","trans-specific topics","transgender people","transphobia","transportation","transsexuals","trends","twitter or X","two-spirit people","universities or colleges","vaccines","vehicle","victim compensation","victim rights","victimization","victims of crimes","violence","violent crimes","voting","voting rights","white supremacy","youth"]
cv_country = ["All","Afghanistan","Aland Islands","Albania","Algeria","American Samoa","Andorra","Angola","Anguilla","Antarctica","Antigua and Barbuda","Argentina","Armenia","Aruba","Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bermuda","Bhutan","Bolivia ","Bonaire, Sint Eustatius and Saba","Bosnia and Herzegovina","Botswana","Bouvet Island","Brazil","British Indian Ocean Territory","British Virgin Islands","Brunei","Bulgaria","Burkina Faso","Burundi","Cabo Verde","Cambodia","Cameroon","Canada","Cayman Islands","Central African Republic","Chad","Chile","China","Christmas Island","Cocos (Keeling) Islands","Colombia","Comoros","Congo (Republic of)","Congo DR","Cook Islands","Costa Rica","Côte d’Ivoire","Croatia","Cuba","Curaçao","Cyprus","Czechia","Denmark","Djibouti","Dominica","Dominican Republic","Ecuador","Egypt","El Salvador","England","Equatorial Guinea","Eritrea","Estonia","Eswatini","Ethiopia","Falkland Islands (Malvinas)","Faroe Islands","Fiji","Finland","France","French Guiana","French Polynesia","French Southern Territories","Gabon","Gambia","Georgia","German Democratic Republic (1949-1990)","Germany","Ghana","Gibraltar","Global","Greece","Greenland","Grenada","Guadeloupe","Guam","Guatemala","Guernsey","Guinea","Guinea-Bissau","Guyana","Haiti","Heard Island and McDonald Islands","Holy See","Honduras","Hong Kong","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Isle of Man","Israel","Italy","Jamaica","Japan","Jersey","Jordan","Kazakhstan","Kenya","Kiribati","Korea DR (North)","Korea Rep. (South) ","Kosovo","Kuwait","Kyrgyzstan","Lao PDR","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Macao","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Marshall Islands","Martinique","Mauritania","Mauritius","Mayotte","Mexico","Micronesia ","Moldova","Monaco","Mongolia","Montenegro","Montserrat","Morocco","Mozambique","Myanmar","Namibia","Nauru","Nepal","Netherlands","New Caledonia","New Zealand","Nicaragua","Niger","Nigeria","Niue","Norfolk Island","North Macedonia","Northern Ireland","Northern Mariana Islands","Norway","Oman","Pakistan","Palau","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Pitcairn","Poland","Portugal","Puerto Rico","Qatar","Réunion","Romania","Russia","Rwanda","Saint Barthélemy","Saint Helena","Saint Kitts and Nevis","Saint Lucia","Saint Martin (French Part)","Saint Pierre and Miquelon","Saint Vincent and the Grenadines","Samoa","San Marino","Sao Tome and Principe","Saudi Arabia","Scotland","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Sint Maarten (Dutch part)","Slovakia","Slovenia","Solomon Islands","Somalia","South Africa","South Georgia and the South Sandwich Islands","South Sudan","Spain","Sri Lanka","State of Palestine","Sudan","Suriname","Svalbard and Jan Mayen Islands","Sweden","Switzerland","Syrian Arab Republic","Tajikistan","Tanzania","Thailand","Timor-Leste (East Timor)","Togo","Tokelau","Tonga","Trinidad and Tobago","Tunisia","Türkiye (Turkey)","Turkmenistan","Turks and Caicos Islands","Tuvalu","Uganda","Ukraine","United Arab Emirates","United Kingdom ","United States of America","Uruguay","US Minor Outlying Islands","US Virgin Islands","Uzbekistan","Vanuatu","Venezuela ","Viet Nam","Wallis and Futuna Islands","West Bank and Gaza","Western Sahara","Yemen","Zambia","Zimbabwe"]
cv_region = ["All","Africa","Northern Africa","Sub-Saharan Africa","Americas","Latin America and the Caribbean","Northern America","Asia","Central Asia","Eastern Asia","South-eastern Asia","Southern Asia","Western Asia","Europe","Eastern Europe","Northern Europe","Southern Europe","Western Europe","Oceania","Australia and New Zealand","Melanesia","Micronesia","Polynesia","Antarctica","All Regions","Other","German Reich (1871-1945) (DXDE)"]
cv_adminLevel = ["All","Administrative District","Administrative Division","Arrondisement","Canton","Census Section","Chiefdom or Ward","Circle","Commune","County","Department","District","District Council","Local Government Area","Municipal Ward or Village Council Area","Municipality","Nation","Prefecture or City","Prefecture","Province","PUMA (USA)","Raion","Regency","Reservation","State","Subdistrict","Sub-prefecture","Traditional Authority","Hamlet or Village ","Zone"]
cv_unitAnalysis = ["All","Event or Process","Family","Geographic Unit","Group","Household","Household Family","Housing Unit","Individual","Media Unit","Object","Organization","Other","Text Unit","Time Unit","Political or Administrative Area"]
cv_longitudinal = ["All","Yes","No","Unknown"]
cv_language = ["All","Abkhazian","Achinese","Acoli","Adangme","Adyghe; Adygei","Afar","Afrihili","Afrikaans","Afro-Asiatic languages","Ainu","Akan","Akkadian","Albanian","Aleut","Algonquian languages","Altaic languages","Amharic","Angika","Apache languages","Arabic","Aragonese","Arapaho","Arawak","Armenian","Aromanian; Arumanian; Macedo-Romanian","Artificial languages","Assamese","Asturian; Bable; Leonese; Asturleonese","Athapascan languages","Australian languages","Austronesian languages","Avaric","Avestan","Awadhi","Aymara","Azerbaijani","Balinese","Baltic languages","Baluchi","Bambara","Bamileke languages","Banda languages","Bantu languages","Basa","Bashkir","Basque","Batak languages","Beja; Bedawiyet","Belarusian","Bemba","Bengali","Berber languages","Bhojpuri","Bihari languages","Bikol","Bini; Edo","Bislama","Blin; Bilin","Blissymbols; Blissymbolics; Bliss","Bokmål, Norwegian; Norwegian Bokmål","Bosnian","Braj","Breton","Buginese","Bulgarian","Buriat","Burmese","Caddo","Catalan; Valencian","Caucasian languages","Cebuano","Celtic languages","Central American Indian languages","Chagatai","Chamic languages","Chamorro","Chechen","Cherokee","Cheyenne","Chibcha","Chichewa; Chewa; Nyanja","Chinese","Chinook jargon","Chipewyan; Dene Suline","Choctaw","Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic","Chuukese","Chuvash","Classical Newari; Old Newari; Classical Nepal Bhasa","Classical Syriac","Coptic","Cornish","Corsican","Cree","Creek","Creoles and pidgins","Creoles and pidgins, English based","Creoles and pidgins, French-based","Creoles and pidgins, Portuguese-based","Crimean Tatar; Crimean Turkish","Croatian","Cushitic languages","Czech","Dakota","Danish","Dargwa","Delaware","Dinka","Divehi; Dhivehi; Maldivian","Dogri","Dogrib","Dravidian languages","Duala","Dutch, Middle (ca.1050-1350)","Flemish","Dutch","Dyula","Dzongkha","Eastern Frisian","Efik","Egyptian (Ancient)","Ekajuk","Elamite","English","","Erzya","Esperanto","Estonian","Ewe","Ewondo","Fang","Fanti","Faroese","Fijian","Filipino","Finnish","Finno-Ugrian languages","Fon","French","French, Middle (ca.1400-1600)","French, Old (842-ca.1400)","Friulian","Fulah","Ga","Gaelic; Scottish Gaelic","Galibi Carib","Galician","Ganda","Gayo","Gbaya","Geez","Georgian","German","German, Middle High (ca.1050-1500)","German, Old High (ca.750-1050)","Germanic languages","Gilbertese","Gondi","Gorontalo","Gothic","Grebo","Greek, Ancient (to 1453)","Greek, Modern (1453-)","Guarani","Gujarati","Gwich'in","Haida","Haitian; Haitian Creole","Hausa","Hawaiian","Hebrew","Herero","Hiligaynon","Himachali languages; Western Pahari languages","Hindi","Hiri Motu","Hittite","Hmong; Mong","Hungarian","Hupa","Iban","Icelandic","Ido","Igbo","Ijo languages","Iloko","Inari Sami","Indic languages","Indo-European languages","Indonesian","Ingush","Interlingua (International Auxiliary Language Association)","Interlingue; Occidental","Inuktitut","Inupiaq","Iranian languages","Irish","Irish, Middle (900-1200)","Irish, Old (to 900)","Iroquoian languages","Italian","Japanese","Javanese","Judeo-Arabic","Judeo-Persian","Kabardian","Kabyle","Kachin; Jingpho","Kalaallisut; Greenlandic","Kalmyk; Oirat","Kamba","Kannada","Kanuri","Kara-Kalpak","Karachay-Balkar","Karelian","Karen languages","Kashmiri","Kashubian","Kawi","Kazakh","Khasi","Khmer","Khoisan languages","Khotanese; Sakan","Kikuyu; Gikuyu","Kimbundu","Kinyarwanda","Kirghiz; Kyrgyz","Klingon; tlhIngan-Hol","Komi","Kongo","Konkani","Korean","Kosraean","Kpelle","Kru languages","Kuanyama; Kwanyama","Kumyk","Kurdish","Kurukh","Kutenai","Ladino","Lahnda","Lamba","Land Dayak languages","Lao","Latin","Latvian","Lezghian","Limburgan; Limburger; Limburgish","Lingala","Lithuanian","Lojban","Low German; Low Saxon; German, Low; Saxon, Low","Lower Sorbian","Lozi","Luba-Katanga","Luba-Lulua","Luiseno","Lule Sami","Lunda","Luo (Kenya and Tanzania)","Lushai","Luxembourgish; Letzeburgesch","Macedonian","Madurese","Magahi","Maithili","Makasar","Malagasy","Malay","Malayalam","Maltese","Manchu","Mandar","Mandingo","Manipuri","Manobo languages","Manx","Maori","Mapudungun; Mapuche","Marathi","Mari","Marshallese","Marwari","Masai","Mayan languages","Mende","Mi'kmaq; Micmac","Minangkabau","Mirandese","Mohawk","Moksha","Mon-Khmer languages","Mongo","Mongolian","Montenegrin","Mossi","Multiple languages","Munda languages","N'Ko","Nahuatl languages","Nauru","Navajo; Navaho","Ndebele, North; North Ndebele","Ndebele, South; South Ndebele","Ndonga","Neapolitan","Nepal Bhasa; Newari","Nepali","Nias","Niger-Kordofanian languages","Nilo-Saharan languages","Niuean","No linguistic content; Not applicable","Nogai","Norse, Old","North American Indian languages","Northern Frisian","Northern Sami","Norwegian","Norwegian Nynorsk; Nynorsk, Norwegian","Nubian languages","Nyamwezi","Nyankole","Nyoro","Nzima","Occitan (post 1500)","Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)","Ojibwa","Oriya","Oromo","Osage","Ossetian; Ossetic","Otomian languages","Pahlavi","Palauan","Pali","Pampanga; Kapampangan","Pangasinan","Panjabi; Punjabi","Papiamento","Papuan languages","Pedi; Sepedi; Northern Sotho","Persian","Persian, Old (ca.600-400 B.C.)","Philippine languages","Phoenician","Pohnpeian","Polish","Portuguese","Prakrit languages","Provençal, Old (to 1500);Occitan, Old (to 1500)","Pushto; Pashto","Quechua","Rajasthani","Rapanui","Rarotongan; Cook Islands Maori","Reserved for local use","Romance languages","Romanian; Moldavian; Moldovan","Romansh","Romany","Rundi","Russian","Salishan languages","Samaritan Aramaic","Sami languages","Samoan","Sandawe","Sango","Sanskrit","Santali","Sardinian","Sasak","Scots","Selkup","Semitic languages","Serbian","Serer","Shan","Shona","Sichuan Yi; Nuosu","Sicilian","Sidamo","Sign Languages","Siksika","Sindhi","Sinhala; Sinhalese","Sino-Tibetan languages","Siouan languages","Skolt Sami","Slave (Athapascan)","Slavic languages","Slovak","Slovenian","Sogdian","Somali","Songhai languages","Soninke","Sorbian languages","Sotho, Southern","South American Indian languages","Southern Altai","Southern Sami","Spanish; Castilian","Sranan Tongo","Standard Moroccan Tamazight","Sukuma","Sumerian","Sundanese","Susu","Swahili","Swati","Swedish","Swiss German; Alemannic; Alsatian","Syriac","Tagalog","Tahitian","Tai languages","Tajik","Tamashek","Tamil","Tatar","Telugu","Tereno","Tetum","Thai","Tibetan","Tigre","Tigrinya","Timne","Tiv","Tlingit","Tok Pisin","Tokelau","Tonga (Nyasa)","Tonga (Tonga Islands)","Tsimshian","Tsonga","Tswana","Tumbuka","Tupi languages","Turkish","Turkish, Ottoman (1500-1928)","Turkmen","Tuvalu","Tuvinian","Twi","Udmurt","Ugaritic","Uighur; Uyghur","Ukrainian","Umbundu","Uncoded languages","Undetermined","Upper Sorbian","Urdu","Uzbek","Vai","Venda","Vietnamese","Volapük","Votic","Wakashan languages","Walloon","Waray","Washo","Welsh","Western Frisian","Wolaitta; Wolaytta","Wolof","Xhosa","Yakut","Yao","Yapese","Yiddish","Yoruba","Yupik languages","Zande languages","Zapotec","Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki","Zenaga","Zhuang; Chuang","Zulu","Zuni"]
cv_restrictions = ["All","Yes","No","Unknown"]

In [7]:
df.columns

Index(['Title', 'URL', 'ResourceType', 'Citation', 'PubDate',
       'CollectDateStart', 'CollectDateEnd', 'Producer', 'Distributor',
       'Description', 'DataMethodType', 'Longitudinal', 'TimeSpan', 'Country',
       'GeographicRegion', 'AdminLevel', 'UnitAnalysis', 'Language', 'Themes',
       'Subjects', 'Restrictions', 'Notes', 'AddedUpdated', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29'],
      dtype='object')

In [20]:

filt_resourcetype1 = (df["ResourceType"]== "Dataset")
filt_resourcetype2 = (df["ResourceType"]!= "All")
        
filt_themes1 = (df["Themes"].notnull() & df["Themes"].str.contains("Opinions and Social Attitudes"))
filt_themes2 = (df["Themes"].isnull() | df["Themes"] != "All")

In [19]:
df.loc[filt_themes2]

,Title,URL,ResourceType,Citation,PubDate,CollectDateStart,CollectDateEnd,Producer,Distributor,Description,...,Restrictions,Notes,AddedUpdated,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29
0,2013-lgb-living-conditions-persondata. Part of...,https://doi.org/10.18712/NSD-NSD2610-V3,Dataset,NaN,2022.0,2012.0,2013.0,Norman Anderssen,Sikt– Norwegian Agency for Shared Services in ...,"""2013 lgb-living-conditions-persondata"" was co...",...,No,"On the website, the collection is named ""Sexua...",23/05/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015 U.S. Transgender Survey (USTS),https://doi.org/10.3886/ICPSR37229,Dataset,"Sandy E. James, National Center for Transgende...",2019.0,2015.0,2015.0,NaN,Inter university Consortium for Political and ...,The 2015 U.S. Transgender Survey (USTS) was co...,...,Yes,NaN,08/05/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020 Census: LGBTQ+,https://www.census.gov/newsroom/press-kits/202...,Website,NaN,2020.0,2019.0,NaN,U.S. Census Bureau,U.S. Census Bureau,The U.S. Census Bureau’s Current Population Su...,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024 LGBTI Inclusion Index: Report on the Pilo...,https://www.undp.org/publications/2024-lgbti-i...,Report,NaN,2024.0,NaN,NaN,United Nations Development Programme (UNDP),NaN,The LGBTI Inclusion Index serves as a global b...,...,No,NaN,05/02/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024 U.S. National Survey on the Mental Health...,https://www.thetrevorproject.org/survey-2024/,Report,Trevor Project (2024). 2024 National Survey on...,2024.0,2023.0,2023.0,Trevor Project,Trevor Project,The Trevor Project’s 2024 U.S. National Survey...,...,No,NaN,24/04/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,Well-Being of LGBTIQ Youth 2013,https://doi.org/10.60686/t-fsd2924,Dataset,NaN,2019.0,2013.0,2013.0,Finnish Social Science Data Archive,Finnish Social Science Data Archive,"The Well-Being of LGBTIQ Youth survey, conduct...",...,Yes,NaN,24/04/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,What is the size of Australia’s sexual minorit...,https://bmcresnotes.biomedcentral.com/articles...,Journal Article,NaN,2020.0,2011.0,2016.0,BMC Research Notes,Springer,The aim is to present updated estimates of the...,...,No,NaN,08/05/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,Williams Institute,https://williamsinstitute.law.ucla.edu/,Website,NaN,NaN,NaN,NaN,NaN,NaN,The Williams Institute conducts independent re...,...,No,Includes data in Reports under the Publication...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,World Values Survey (WVS),https://www.worldvaluessurvey.org/WVSDocumenta...,Dataset,NaN,NaN,1981.0,NaN,World Values Survey Association,NaN,The World Values Survey (WVS) is an internatio...,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,LGBTQ+ Social Justice and Culture,https://coherentdigital.net/products/history-c...,"Finding Aid, Collection",NaN,NaN,NaN,NaN,History Commons (formerly Accessible Archives),Coherent Digital,It indexes the full text of openly available a...,...,Yes,subscription,04/06/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN